server:
  port: 8080




jwt:
  header: Authorization
  #HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
  #echo "YOPLE-AES512-SecretKeyYOPLE-AES512-SecretKeyYOPLE-AES512-SecretKeyYOPLE-AES512-SecretKeyYOPLE-AES512-SecretKey"|base64
  secret: WU9QTEUtQUVTNTEyLVNlY3JldEtleVlPUExFLUFFUzUxMi1TZWNyZXRLZXlZT1BMRS1BRVM1MTItU2VjcmV0S2V5WU9QTEUtQUVTNTEyLVNlY3JldEtleVlPUExFLUFFUzUxMi1TZWNyZXRLZXk=
  access-token-validity-in-seconds: 600 # 1 Days
  refresh-token-validity-in-seconds: 1800 # 10 Days

#"YOPLE-AES512-SecretKey"를 SHA256암호화 후 앞에서 32Byte
aes-secret: 7BC19394C7DF9047349B25886954C9B8

yople:
  sens:
    svc_id: "ncp:sms:kr:279058593171:sms-service"
    host: "https://sens.apigw.ntruss.com"
    url: "/sms/v2/services/"
    type: "/messages"
    accessKey: "kNKPMYVwhTp3uIYbek9i"
    secretKey: "XouxuOyjVhekRsLBqCEuocX9ghAugujpI4gvUlXD"
    message:
      type: "SMS"
      content_type: "COMM"
      country_code: "82"



